import type { GenerationTask } from './types'

const now = Date.now()

export const generationTaskSeed: GenerationTask[] = [
  {
    id: 'task-001',
    type: 'video',
    status: 'running',
    prompt: 'Кинематографичный пролет над ночным городом с теплым неоновым светом и дождем',
    model: 'Kling 2.1',
    createdAt: now - 1000 * 60 * 18,
    updatedAt: now - 1000 * 20,
    progress: 42,
    credits: 28,
    etaSec: 54,
    durationSec: 120,
  },
  {
    id: 'task-002',
    type: 'image',
    status: 'running',
    prompt: 'Плакат продукта ERA2 в теплой угольной палитре, крупная типографика',
    model: 'Nano Banana',
    createdAt: now - 1000 * 60 * 12,
    updatedAt: now - 1000 * 10,
    progress: 76,
    credits: 6,
    etaSec: 12,
    durationSec: 38,
  },
  {
    id: 'task-003',
    type: 'text',
    status: 'queued',
    prompt: 'Сгенерировать структуру лендинга для сервиса аналитики рекламных кампаний',
    model: 'GPT-5 mini',
    createdAt: now - 1000 * 60 * 9,
    updatedAt: now - 1000 * 60 * 9,
    progress: 0,
    credits: 2,
    etaSec: 18,
  },
  {
    id: 'task-004',
    type: 'audio',
    status: 'queued',
    prompt: 'Спокойный голос диктора для проморолика, 30 секунд, русский язык',
    model: 'ElevenLabs Voice',
    createdAt: now - 1000 * 60 * 7,
    updatedAt: now - 1000 * 60 * 7,
    progress: 0,
    credits: 14,
    etaSec: 75,
  },
  {
    id: 'task-005',
    type: 'image',
    status: 'queued',
    prompt: 'Минималистичная обложка для статьи про нейросети и продакшен-пайплайны',
    model: 'Midjourney V7',
    createdAt: now - 1000 * 60 * 5,
    updatedAt: now - 1000 * 60 * 5,
    progress: 0,
    credits: 8,
    etaSec: 31,
  },
  {
    id: 'task-006',
    type: 'video',
    status: 'queued',
    prompt: 'Вертикальный ролик 9:16: рука рисует интерфейс будущего на стекле',
    model: 'Runway Gen-4',
    createdAt: now - 1000 * 60 * 3,
    updatedAt: now - 1000 * 60 * 3,
    progress: 0,
    credits: 32,
    etaSec: 140,
  },
  {
    id: 'task-007',
    type: 'text',
    status: 'done',
    prompt: 'Подготовить 10 вариантов заголовков для страницы тарифов',
    model: 'Claude Sonnet',
    createdAt: now - 1000 * 60 * 44,
    updatedAt: now - 1000 * 60 * 39,
    progress: 100,
    credits: 1,
    durationSec: 24,
    completedAt: now - 1000 * 60 * 39,
  },
  {
    id: 'task-008',
    type: 'image',
    status: 'done',
    prompt: 'Серия иконок для категорий: текст, изображение, видео, аудио',
    model: 'Flux Pro',
    createdAt: now - 1000 * 60 * 58,
    updatedAt: now - 1000 * 60 * 55,
    progress: 100,
    credits: 5,
    durationSec: 42,
    completedAt: now - 1000 * 60 * 55,
  },
  {
    id: 'task-009',
    type: 'audio',
    status: 'failed',
    prompt: 'Энергичный джингл для короткого рекламного видео',
    model: 'Suno',
    createdAt: now - 1000 * 60 * 25,
    updatedAt: now - 1000 * 60 * 21,
    progress: 51,
    credits: 10,
    error: 'Модель временно недоступна',
  },
  {
    id: 'task-010',
    type: 'text',
    status: 'canceled',
    prompt: 'Переписать описание продукта в более деловом тоне',
    model: 'GPT-5',
    createdAt: now - 1000 * 60 * 32,
    updatedAt: now - 1000 * 60 * 29,
    progress: 17,
    credits: 2,
  },
]
